defaults:
- config

paths:
  results_dir: ${paths.root_dir}/results/pref
  sweep_dir: ${paths.root_dir}/results_sweep/pref


hydra:
  run:
    dir: ${paths.results_dir}/${now:%Y%m%d_%H%M%S}_nqu=${data.nq_update}

  sweep:
    # dir: ${paths.sweep_dir}/${now:%Y%m%d_%H%M%S}_nitersUpdate=${niters_update}_lr=${learning_rate}_ekfM=${ekf.M}_iekf=${ekf.iekf}_ekfLr=${ekf.learning_rate}_ekfDn=${ekf.dynamics_noise}_ekfPn=${ekf.prior_noise}_ekfOn=${ekf.obs_noise}_ekfAcq=${ekf.acq}_acq=${acq}
    dir: ${paths.sweep_dir}/${now:%Y%m%d_%H%M%S}_nitersUpdate=${niters_update}_lr=${learning_rate}_acq=${acq}_M=${M}_${dir_extra}
    subdir: ${hydra.job.num}_task=${hydra.runtime.choices.task}
