defaults:
- _self_
- task: synthetic
- data: base
- network: small
- mcmc: mh
- ekf: ekf
- sgd: sgd
- rl: iql
- optional local: default # specifies project dir & wandb login, goes after wandb
# - optional run: debug
- hydra: default

fhat: linear
chunk_size: 128
seed_vmap: True # good for 3 seeds or under

# * sanity check for active learning acquisition functions
sanity: False
sanity_frac: 0.01 # fraction of non-duplicates in the query pool. 1% of nq_train=5000 is 50, nq_update=50 

wandb:
  entity: "yutaizhou"
  project: "bnn_pref"

  # name: null # display name of run in GUI, set in code
  # id: # for resuming
  group: null # organize sweeps / group multiple runs as one experiment
  # job_type: null # set in code
  tags:  null # editable in GUI, as well as a resumed run 

  # mode:  # online, offline, disabled


paths:
  results_dir: ${paths.root_dir}/results
  sweep_dir: ${paths.root_dir}/results_sweep
  output_dir: ${hydra:runtime.output_dir} # set by results_dir & sweep_dir in hydra config
  ckpts_dir: ${paths.output_dir}/ckpts

  prefcc:
    data_dir: ${paths.prefcc_dir}


seed: -1 # for jr.key() - initial random seeding
seeds: 1 # for jax.vmap() - number of seeds to run
show_fig: False
save_fig: False