defaults:
- config

paths:
  results_dir: ${paths.root_dir}/results/pref
  sweep_dir: ${paths.root_dir}/results_sweep/pref


hydra:
  run:
    dir: ${paths.results_dir}/${now:%Y%m%d_%H%M%S}_nqu=${data.nq_update}

  sweep:
    dir: ${paths.sweep_dir}/${now:%Y%m%d_%H%M%S}_updateAll=${update_all}_nitersUpdate=${niters_update}_lr=${learning_rate}_ekfM=${ekf.M}_ekfAcq=${ekf.acq}_acq=${acq}
    subdir: ${hydra.job.num}_task=${hydra.runtime.choices.task}
