defaults:
- _self_
- task: synthetic
- mcmc: mh
- ekf: ekf
- data: base
- optional local: default # specifies project dir & wandb login, goes after wandb
# - optional run: debug
- hydra: default

f: linear
fhat: ${.f}

paths:
  results_dir: ${paths.root_dir}/results
  sweep_dir: ${paths.root_dir}/results_sweep
  output_dir: ${hydra:runtime.output_dir}

  prefcc:
    data_dir: /scr/shared/prefcc/
  tdmpc2:
    data_dir: /scr/shared/tdmpc2/
    mt30_raw_dir: ${.data_dir}/tdmpc2_mt30_raw/
    mt30_processed_dir: ${.data_dir}/tdmpc2_mt30_processed/
    mt80_raw_dir: ${.data_dir}/tdmpc2_mt80_raw/
    mt80_processed_dir: ${.data_dir}/tdmpc2_mt80_processed/


seed: -1 # for jr.key()
seeds: 1 # for jax.vmap()
show_fig: False
save_fig: False