defaults:
- _self_
- task: synthetic
- network: small
- mcmc: mh
- ekf: ekf
- sgd: sgd
- data: base
- optional local: default # specifies project dir & wandb login, goes after wandb
# - optional run: debug
- hydra: default

fhat: linear
chunk_size: 128
seed_vmap: True # good for 3 seeds or under

# * sanity check for active learning acquisition functions
sanity: False
sanity_frac: 0.01 # fraction of non-duplicates in the query pool. 1% of nq_train=5000 is 50, nq_update=50 

paths:
  results_dir: ${paths.root_dir}/results
  sweep_dir: ${paths.root_dir}/results_sweep
  output_dir: ${hydra:runtime.output_dir}

  prefcc:
    data_dir: ${paths.prefcc_dir}


seed: -1 # for jr.key() - initial random seeding
seeds: 1 # for jax.vmap() - number of seeds to run
show_fig: False
save_fig: False