# * NN model
learning_rate: 0.001
hidden_sizes:
  - 32
  - 32

# * active learning
active: False
M: 20 # num models to sample for mutual information acquisition function

# * Subspace Init w/ SGD 
niters: 100  # Total number of GD steps on warmup data
bs: 1 # -1 for full batch GD. Otherwise, mini-batch SGD
l2_reg: 0

warm_burns: 20
thinning: 2
sub_dim: 40
rnd_proj: False

# * Subspace Inference w/ EKF
# intuition on Kalman Gain - stronger posterior update <- dec obs_noise, inc prior_noise
prior_noise: 0.01
dynamics_noise: 0.0001 # small Gaussian drift on NN params, where we assume constant dynamics
obs_noise: 0.01  # noise on emissions, which for pref learning is always +1 for traj2 > traj 1 # 1 rly affects bma 
iekf: 2 # iterated EKF: multiple linearization of measurement model around current belief instead of prior belief


# * following is just for convenience in hydra CLI overrides
cls:
  niters: ${..niters}
  batch_size: ${..bs}
  l2_reg: ${..l2_reg}
  warm_burns: ${..warm_burns}
  thinning: ${..thinning}
  sub_dim: ${..sub_dim}
  rnd_proj: ${..rnd_proj}
  prior_noise: ${..prior_noise}
  dynamics_noise: ${..dynamics_noise}
  obs_noise: ${..obs_noise}
  iekf: ${..iekf}
  mi_samples: ${..M}