# * model ensembling & active learning
# ensembling only used for computing predictive & acquisition function (not training)
active: ${..active}
M: ${..M}
# M: 100
use_vmap: ${..use_vmap} # turned off for scalability experiments. whether to use vectorized NN prediction
chunk_size: ${..chunk_size}
acq: ${..acq}


# * NN model
hidden_sizes: ${network.hidden_sizes}
n_splits: ${network.n_splits}
dropout_prob: 0.0

# * Subspace Init w/ SGD 
bs: ${..bs} # -1 for full batch GD. Otherwise, mini-batch SGD
niters_init: 420  # Total number of GD steps on warmup data
learning_rate: 0.0001
momentum: 0.9
l2_reg: 0

# subspace construction, SVD takes full space param array as X[warm_burns::thinning], only keep the top sub_dim components
warm_burns: 20
thinning: 2
sub_dim: 200
rnd_proj: False # True will use random projection instead of SVD for subspace construction

# * Subspace Inference w/ EKF
# stronger posterior update: inc prior_noise, dec obs_noise
# weaker posterior update: dec prior_noise, inc obs_noise
dynamics_noise: 0.0001 # assume constant dynamics w/ gaussian drift on NN params
prior_noise: 0.07
obs_noise: 0.07  # noise on emissions, which for pref learning is always +1 for traj2 > traj 1 # 1 rly affects bma 
iekf: 2 # iterated EKF: multiple linearization of measurement model around current belief instead of prior belief

# prior/obs:
# strong: 0.1 / 0.03
# neurips: 0.07 / 0.07
# weak: 0.03 / 0.1