learning_rate: 0.001

warm_obs: 200 # num samples to use for SGD belief initalization
n_steps: -1 # num samples to do EKF filtering (if -1, use all remaining afer warm_obs)

hidden_sizes:
  - 32
  - 32

cls:
  # Subspace Init w/ SGD
  n_iterates: 100  # Total number of GD steps on warmup data
  batch_size: -1 # -1 for full batch GD. Otherwise, mini-batch SGD
  l2_reg: 0

  warm_burns: 20
  thinning: 2
  sub_dim: 40
  rnd_proj: False
  
  # Subspace Inference w/ EKF
  # prior_noise: 0.0001 # variance
  # dynamics_noise: 0.0
  # obs_noise: 0.0

  prior_noise: 0.01  # Increased from 0.0001
  dynamics_noise: 0.001  # Increased from 0.0
  obs_noise: 0.01  # Increased from 0.0