alg_sets = dict(
    all=["ekf", "sgd", "do", "laplace", "llmcmc"],
    ekf=["ekf"],
    visual=["ekf", "sgd", "do"],
)
task_sets = dict(
    main=[
        # # * D4RL
        "cheetahRandom",
        "cheetahMediumReplay",
        "cheetahMediumExpert",
        "hopperRandom",
        "hopperMediumReplay",
        "hopperMediumExpert",
        "walkerRandom",
        "walkerMediumReplay",
        "walkerMediumExpert",
        "penHuman",
        # "penExpert",
        # "penCloned",
        # "kitchenComplete",
        # "kitchenPartial",
        # "kitchenMixed",
        # "mazeUDense",
        "mazeMediumDense",
        "mazeLargeDense",
    ],
    unirlhf=[
        "uniCheetahMedium",
        "uniCheetahMediumReplay",
        "uniCheetahMediumExpert",
        "uniHopperMedium",
        "uniHopperMediumReplay",
        "uniHopperMediumExpert",
        "uniWalkerMedium",
        "uniWalkerMediumReplay",
        "uniWalkerMediumExpert",
        "uniPenHuman",
        "uniPenCloned",
    ],
    visual3=[
        "vcheetahMediumExpert",
        "vhumanoidMediumExpert",
        "vwalkerMediumExpert",
    ],
    visual=[
        "vcheetahRandom",
        "vcheetahMediumReplay",
        "vcheetahMediumExpert",
        "vhumanoidRandom",
        "vhumanoidMediumReplay",
        "vhumanoidMediumExpert",
        "vwalkerRandom",
        "vwalkerMediumReplay",
        "vwalkerMediumExpert",
    ],
    soar=[
        "soarBlueBlockPutIn",
        "soarCarrotRemove",
        "soarCloseDrawer",
        "soarEggplantPutIn",
        "soarEggplantRemove",
        "soarMushroomRemove",
        "soarSpoonMoveLeft",
    ],
    soar3=[
        "soarBlueBlockPutIn",
        # "soarCarrotRemove",
        # "soarCloseDrawer",
        # "soarEggplantPutIn",
        "soarEggplantRemove",
        "soarMushroomRemove",
        # "soarSpoonMoveLeft",
    ],
)
