alg_sets = dict(
    all=["ekf", "sgd", "do", "laplace", "llmcmc"],
    ekf=["ekf"],
)
task_sets = dict(
    neurips=[
        # # * D4RL
        # "cheetahRandom",
        "cheetahMediumReplay",
        "cheetahMediumExpert",
        "hopperRandom",
        "hopperMediumReplay",
        "hopperMediumExpert",
        "walkerRandom",
        "walkerMediumReplay",
        "walkerMediumExpert",
        "penHuman",
        "penExpert",
        # "penCloned",
        # "kitchenComplete",
        # "kitchenPartial",
        # "kitchenMixed",
        "mazeUDense",
        "mazeMediumDense",
        # "mazeLargeDense",
    ],
    iclr=[
        # # * D4RL
        "cheetahRandom",
        "cheetahMediumReplay",
        "cheetahMediumExpert",
        "hopperRandom",
        "hopperMediumReplay",
        "hopperMediumExpert",
        "walkerRandom",
        "walkerMediumReplay",
        "walkerMediumExpert",
        "penHuman",
        # "penExpert",
        # "penCloned",
        # "kitchenComplete",
        # "kitchenPartial",
        # "kitchenMixed",
        # "mazeUDense",
        "mazeMediumDense",
        "mazeLargeDense",
    ],
    unirlhf=[
        "uniCheetahMedium",
        "uniCheetahMediumReplay",
        "uniCheetahMediumExpert",
        "uniHopperMedium",
        "uniHopperMediumReplay",
        "uniHopperMediumExpert",
        "uniWalkerMedium",
        "uniWalkerMediumReplay",
        "uniWalkerMediumExpert",
        "uniPenHuman",
        "uniPenCloned",
    ],
    test=[
        "cheetahMediumReplay",
        "hopperMediumReplay",
        "walkerMediumReplay",
        "penHuman",
        "mazeMediumDense",
    ],
    visual3=[
        "vcheetahMediumExpert",
        "vhumanoidMediumExpert",
        "vwalkerMediumExpert",
    ],
    visual5=[
        # "vcheetahRandom",
        # "vcheetahMediumReplay",
        "vcheetahMediumExpert",
        # "vhumanoidRandom",
        # "vhumanoidMediumReplay",
        "vhumanoidMediumExpert",
        "vwalkerRandom",
        "vwalkerMediumReplay",
        "vwalkerMediumExpert",
    ],
    visual9=[
        "vcheetahRandom",
        "vcheetahMediumReplay",
        "vcheetahMediumExpert",
        "vhumanoidRandom",
        "vhumanoidMediumReplay",
        "vhumanoidMediumExpert",
        "vwalkerRandom",
        "vwalkerMediumReplay",
        "vwalkerMediumExpert",
    ],
)
