# * last layer MCMC agent & active learning
active: ${..active}
M: ${..M}
# M: 100
use_vmap: ${..use_vmap} # turned off for scalability experiments. whether to use vectorized NN training & prediction
chunk_size: ${..chunk_size}
acq: ${..acq} # "infogain" or "disagreement"
max_buffer_size: ${..max_buffer_size} # for keeping observed queries for training. keep it roughly around `nq_updates`

# * NN model
hidden_sizes: ${network.hidden_sizes}
n_splits: ${network.n_splits}
dropout_prob: 0.0
encoder: ${network.encoder}

# * Init + Update
bs: ${..bs}
l2_reg: ${..l2_reg}
learning_rate: ${..learning_rate}
niters_init: ${..niters_init}  # Total number of GD steps on warmup data
niters_update: ${..niters_update} # train sgd longer for better MAP estimate for laplace

# Laplace hyperparameters
prior_prec: 1000
curv_type: "full" # "full" or "diagonal"