# * last layer MCMC agent & active learning
active: ${..active}
M: ${..M}
# M: 100
use_vmap: ${..use_vmap} # turned off for scalability experiments. whether to use vectorized NN training & prediction
chunk_size: ${..chunk_size}
acq: ${..acq} # "infogain" or "disagreement"
max_buffer_size: ${..max_buffer_size} # for keeping observed queries for training. keep it roughly around `nq_updates`

# * NN model
hidden_sizes: ${network.hidden_sizes}
n_splits: ${network.n_splits}
dropout_prob: 0.0

# * Init + Update
bs: ${..bs}
l2_reg: ${..l2_reg}

niters_init: ${..niters_init}  # Total number of GD steps on warmup data
# update_all=True: updates for `niters_update` iterations on all queries seen so far in the buffer. 
# update_all=False: updates one iteration on most recent query
# make sure to adjust `learning_rate` according to update strategy
# update_all: True 
update_all: ${..update_all}
niters_update: ${..niters_update}
learning_rate: ${..learning_rate}
# mcmc hyperparameters
prior_prec: 0.2