learning_rate: 0.001
momentum: 0.9

warm_obs: 200 # 0
n_trials: 1

hidden_sizes:
  - 32
  - 32

cls:
  # Subspace Init w/ SGD
  warm_epochs: 100 # 6
  warm_burns: 40
  sub_dim: 40 # 3
  rnd_proj: False
  
  # Subspace Inference w/ EKF
  prior_noise: 0.0001 # variance
  dynamics_noise: 0.0
  obs_noise: 0.0