# * NN model
use_vmap: True
learning_rate: 0.001
hidden_sizes:
  - 32
  - 32

# * active learning
active: False
M: 15 # ensemble size

# * Init
niters: 100  # Total number of GD steps on warmup data
bs: 1 # -1 for full batch GD. Otherwise, mini-batch SGD
l2_reg: 0

# * Update
cls:
  n_models: ${..M}
  l2_reg: ${..l2_reg}
  niters: ${..niters}
  batch_size: ${..bs}
  chunk_size: ${...chunk_size}
  use_vmap: ${..use_vmap}